on:
  workflow_call:

jobs:
  tsc:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 4
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore node_modules for web
        id: cache-web
        uses: actions/cache@v3
        with:
          path: ./web/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('./web/pnpm-lock.yaml') }}
      - name: Install web dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile
      - name: Generate config files
        run: pnpm create-generated-files
      - name: Run TypeScript typechecking for app
        run: pnpm run typecheck
      - name: Run TypeScript typechecking for scripts
        run: pnpm run typecheck --project tsconfig.node.json
